name: 'lint-test-ui'

on:
  pull_request:
    path:
      - ui
    branches:
      - master

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Use Node.js 20.11
        uses: actions/setup-node@v4
        with:
          node-version: 20.11
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test
