name: 'lint-test-api'

on:
  pull_request:
    path:
      - api
    branches:
      - master

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    env:
      NODE_ENV: test
      LOGGER_LEVEL: debug
      DISCORD_TOKEN: DISCORD_TOKEN
      DISCORD_CLIENT_ID: DISCORD_CLIENT_ID
      DISCORD_GUILD_ID: DISCORD_GUILD_ID

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Use Node.js 20.11
        uses: actions/setup-node@v4
        with:
          node-version: 20.11
          cache: 'npm'
          cache-dependency-path: api/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test
